I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
WindowsError: [Error 32] 

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\mbin9\Documents\renpy-7.3.5-sdk\renpy\bootstrap.py", line 316, in bootstrap
    renpy.main.main()
  File "C:\Users\mbin9\Documents\renpy-7.3.5-sdk\renpy\main.py", line 534, in main
    renpy.dump.dump(False)
  File "C:\Users\mbin9\Documents\renpy-7.3.5-sdk\renpy\dump.py", line 255, in dump
    os.rename(new, args.json_dump)
WindowsError: [Error 32] 

Windows-8-6.2.9200
Ren'Py 7.3.5.606
nareyeon 1.0
Sat Feb 15 20:12:42 2020
